const $=id=>document.getElementById(id);const cities=[];let hotelSeq=0,notesEdited=false,suggestTimer;
const escapeHtml=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const cityAliases={
'취리히':'Zurich','루체른':'Lucerne','인터라켄':'Interlaken','체르마트':'Zermatt','그린델발트':'Grindelwald','융프라우':'Jungfrau','베른':'Bern','제네바':'Geneva','몽트뢰':'Montreux','로잔':'Lausanne',
'프라하':'Prague','체스키크룸로프':'Cesky Krumlov','부다페스트':'Budapest','비엔나':'Vienna','빈':'Vienna','브라티슬라바':'Bratislava','자그레브':'Zagreb','두브로브니크':'Dubrovnik','스플리트':'Split','블레드':'Bled','류블랴나':'Ljubljana','플리트비체':'Plitvice Lakes','부쿠레슈티':'Bucharest','소피아':'Sofia','베오그라드':'Belgrade','사라예보':'Sarajevo','스코페':'Skopje','티라나':'Tirana',
'캘거리':'Calgary','밴프':'Banff','레이크루이스':'Lake Louise','재스퍼':'Jasper','토론토':'Toronto','퀘벡':'Quebec City','몬트리올':'Montreal','뉴욕':'New York','로스앤젤레스':'Los Angeles','라스베이거스':'Las Vegas','샌프란시스코':'San Francisco','올랜도':'Orlando',
'도쿄':'Tokyo','오사카':'Osaka','교토':'Kyoto','삿포로':'Sapporo','후쿠오카':'Fukuoka','홍콩':'Hong Kong','마카오':'Macao','타이베이':'Taipei','방콕':'Bangkok','치앙마이':'Chiang Mai','싱가포르':'Singapore','시드니':'Sydney','멜버른':'Melbourne','오클랜드':'Auckland','퀸스타운':'Queenstown'};
const specialCoords={
'레이크루이스':{name:'레이크루이스',country:'캐나다',country_code:'CA',latitude:51.4254,longitude:-116.1773,admin1:'앨버타'},
'융프라우':{name:'융프라우',country:'스위스',country_code:'CH',latitude:46.5368,longitude:7.9626,admin1:'베른'},
'플리트비체':{name:'플리트비체',country:'크로아티아',country_code:'HR',latitude:44.8654,longitude:15.5820,admin1:'리카센'},
'그린델발트':{name:'그린델발트',country:'스위스',country_code:'CH',latitude:46.6242,longitude:8.0414,admin1:'베른'} };
function showError(msg){$('error').textContent=msg;$('error').classList.add('show');$('error').scrollIntoView({behavior:'smooth',block:'center'})}function clearError(){$('error').classList.remove('show')}
function renderCities(){
 $('cityChips').innerHTML=cities.map((c,i)=>`<span class="chip">${escapeHtml(c.label)}${c.country?`<small>${escapeHtml(c.country)}</small>`:''}<button type="button" data-remove="${i}">×</button></span>`).join('');
 $('cityCount').textContent=`${cities.length} / 5개 선택`;
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cities.splice(+b.dataset.remove,1);renderCities();autoNotes(false)});
}
async function searchPlaces(query){
 const q=query.trim();if(q.length<2)return[];if(specialCoords[q])return[specialCoords[q]];
 const terms=[q,cityAliases[q]].filter(Boolean);let found=[];
 for(const term of terms){for(const lang of ['ko','en']){try{const u=new URL('https://geocoding-api.open-meteo.com/v1/search');u.search=new URLSearchParams({name:term,count:'8',language:lang,format:'json'});const r=await fetch(u);if(!r.ok)continue;const j=await r.json();if(j.results?.length){found.push(...j.results);break}}catch{}}if(found.length)break}
 const seen=new Set();return found.filter(x=>{const k=`${x.latitude},${x.longitude}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,6)
}
function renderSuggestions(items){const box=$('suggestions');if(!items.length){box.innerHTML='';box.classList.remove('open');return}box.classList.add('open');box.innerHTML=items.map((x,i)=>`<button type="button" class="suggestion" data-s="${i}"><b>${escapeHtml(x.name)}</b><small>${escapeHtml([x.admin1,x.country].filter(Boolean).join(' · '))}</small></button>`).join('');box.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>selectCity(items[+b.dataset.s]))}
function selectCity(x){if(cities.length>=5)return showError('여행지는 최대 5개까지 입력할 수 있습니다.');const key=`${x.latitude},${x.longitude}`;if(cities.some(c=>`${c.latitude},${c.longitude}`===key))return showError('이미 추가한 도시입니다.');cities.push({label:$('cityInput').value.trim()||x.name,name:x.name,country:x.country||'',country_code:x.country_code||'',latitude:x.latitude,longitude:x.longitude,admin1:x.admin1||''});$('cityInput').value='';renderSuggestions([]);renderCities();autoNotes(false);clearError()}
async function addCity(){const q=$('cityInput').value.trim();if(!q)return;const items=await searchPlaces(q);if(!items.length)return showError(`‘${q}’의 위치를 찾지 못했습니다. 도시명이나 영문명을 확인해 주세요.`);selectCity(items[0])}
$('cityInput').addEventListener('input',()=>{clearTimeout(suggestTimer);suggestTimer=setTimeout(async()=>renderSuggestions(await searchPlaces($('cityInput').value)),300)});$('cityInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addCity()}});$('addCity').onclick=addCity;
function areaTips(){const text=cities.map(c=>`${c.label} ${c.name} ${c.country} ${c.admin1}`).join(' ').toLowerCase();const tips=[];
 if(/banff|밴프|jasper|재스퍼|lake louise|레이크루이스|jungfrau|융프라우|zermatt|체르마트|interlaken|인터라켄|grindelwald|그린델발트|alps|알프스|switzerland|스위스/.test(text))tips.push('산악 지역은 도심보다 기온이 낮고 날씨 변화가 빠르므로, 얇은 옷을 여러 겹 준비하고 방수·방풍 재킷을 챙겨 주세요.');
 if(/dubrovnik|두브로브니크|split|스플리트|venice|베네치아|barcelona|바르셀로나|rome|로마|athens|아테네|mediterranean|지중해/.test(text))tips.push('햇볕이 강하고 야외 보행 시간이 길 수 있으니 모자, 선글라스, 자외선 차단제와 편한 신발을 준비해 주세요.');
 if(/tokyo|도쿄|osaka|오사카|kyoto|교토|hong kong|홍콩|taipei|타이베이|singapore|싱가포르|bangkok|방콕/.test(text))tips.push('대중교통과 도보 이동이 많으므로 편한 신발을 준비하고, 실내 냉방과 갑작스러운 비에 대비해 얇은 겉옷과 작은 우산을 챙겨 주세요.');
 if(/new york|뉴욕|chicago|시카고|toronto|토론토|montreal|몬트리올|quebec|퀘벡|prague|프라하|budapest|부다페스트|vienna|비엔나|빈/.test(text))tips.push('도심 관광은 도보 이동이 많고 아침저녁 기온 차이가 날 수 있으니 편한 운동화와 가벼운 겉옷을 준비해 주세요.');
 if(/las vegas|라스베이거스|dubai|두바이|phoenix|피닉스/.test(text))tips.push('낮에는 매우 덥고 건조하지만 실내 냉방은 강할 수 있으니 충분한 수분과 얇은 겉옷을 함께 준비해 주세요.');
 if(/auckland|오클랜드|queenstown|퀸스타운|sydney|시드니|melbourne|멜버른|new zealand|뉴질랜드|australia|호주/.test(text))tips.push('남반구는 한국과 계절이 반대이며 하루에도 기온 변화가 클 수 있으니 출발 직전 현지 예보를 다시 확인해 주세요.');
 if(!tips.length&&cities.length)tips.push(`${cities.map(c=>c.label).join('·')} 지역은 도시별 기온과 강수 차이가 있을 수 있으니, 출발 직전 각 도시의 예보를 다시 확인하고 겹쳐 입기 좋은 옷을 준비해 주세요.`);
 if(cities.length>1)tips.push('여러 도시를 이동하는 일정이므로 한 도시의 날씨만 보지 말고 각 지역의 최고·최저기온을 함께 확인해 주세요.');
 tips.push('장시간 도보 관광에 대비해 미끄럽지 않고 편안한 신발을 준비해 주세요.','출발 전 확정 일정, 공항 미팅 시간, 수하물 규정과 여권 유효기간을 다시 확인해 주세요.');return [...new Set(tips)].map(x=>'• '+x).join('\n')}
function autoNotes(force){if(!force&&notesEdited)return;$('notes').value=areaTips();$('notesStatus').textContent=cities.length?'입력한 도시를 기준으로 자동 생성되었습니다. 필요에 맞게 수정하세요.':'여행지를 추가하면 자동 안내가 생성됩니다.';notesEdited=false}
$('notes').addEventListener('input',()=>{notesEdited=true;$('notesStatus').textContent='직원이 문구를 수정했습니다. 도시 변경 시 자동으로 덮어쓰지 않습니다.'});$('regenerateNotes').onclick=()=>autoNotes(true);
function addHotel(data={}){hotelSeq++;const el=document.createElement('article');el.className='hotel';el.innerHTML=`<div class="hotelbar"><strong>호텔</strong><button type="button" class="remove">삭제</button></div><div class="hotelgrid"><input class="field hotel-name" placeholder="호텔명 *" value="${escapeHtml(data.name||'')}"><input class="field hotel-city" placeholder="도시 *" value="${escapeHtml(data.city||'')}"><input class="field wide hotel-address" placeholder="주소 또는 지역 (선택)" value="${escapeHtml(data.address||'')}"><input class="field wide hotel-note" placeholder="조식, 객실, 특이사항 (선택)" value="${escapeHtml(data.note||'')}"></div>`;el.querySelector('.remove').onclick=()=>{el.remove();renumberHotels()};$('hotels').appendChild(el);renumberHotels()}
function renumberHotels(){document.querySelectorAll('.hotel').forEach((h,i)=>h.querySelector('strong').textContent=`호텔 ${i+1}`)}function collectHotels(){return[...document.querySelectorAll('.hotel')].map(h=>({name:h.querySelector('.hotel-name').value.trim(),city:h.querySelector('.hotel-city').value.trim(),address:h.querySelector('.hotel-address').value.trim(),note:h.querySelector('.hotel-note').value.trim()})).filter(h=>h.name||h.city)}$('addHotel').onclick=()=>addHotel();addHotel();
function bytesToB64url(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function encodeData(obj){const raw=new TextEncoder().encode(JSON.stringify(obj));if('CompressionStream'in window){try{const cs=new CompressionStream('gzip'),w=cs.writable.getWriter();await w.write(raw);await w.close();return'g'+bytesToB64url(new Uint8Array(await new Response(cs.readable).arrayBuffer()))}catch{}}return'n'+bytesToB64url(raw)}
function futureDate(m){const d=new Date();d.setMonth(d.getMonth()+m);return d.toISOString()}function validUrl(v){try{return/^https?:$/.test(new URL(v).protocol)}catch{return false}}
function shortenUrl(url){return new Promise((resolve,reject)=>{const cb='isgd_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(()=>done(new Error('timeout')),12000);function done(err,val){clearTimeout(timer);delete window[cb];s.remove();err?reject(err):resolve(val)}window[cb]=d=>d?.shorturl?done(null,d.shorturl):done(new Error(d?.errormessage||'shorten failed'));s.onerror=()=>done(new Error('network'));s.src=`https://is.gd/create.php?format=json&callback=${cb}&url=${encodeURIComponent(url)}`;document.head.appendChild(s)})}
$('generate').onclick=async()=>{clearError();const scheduleUrl=$('scheduleUrl').value.trim(),guide=$('guideInfo').value.trim(),hotels=collectHotels();if(!cities.length)return showError('여행지를 1개 이상 입력해 주세요.');if(!validUrl(scheduleUrl))return showError('확정 일정 URL을 http 또는 https 주소로 입력해 주세요.');if(!guide)return showError('가이드 정보를 입력해 주세요.');if(!hotels.length||hotels.some(h=>!h.name||!h.city))return showError('확정 호텔의 호텔명과 도시를 모두 입력해 주세요.');const btn=$('generate');btn.disabled=true;btn.textContent='안내 링크 생성 중...';try{const payload={v:3,cities:cities.map(c=>({...c})),scheduleUrl,guide,hotels,notes:$('notes').value.trim(),createdAt:new Date().toISOString(),expiresAt:futureDate(+$('expiryMonths').value)};const token=await encodeData(payload),base=new URL('../travel-guide/',location.href);base.searchParams.set('d',token);const longUrl=base.href;let finalUrl=longUrl,shortened=false;try{btn.textContent='단축 URL 생성 중...';finalUrl=await shortenUrl(longUrl);shortened=true}catch{}$('generatedLink').value=finalUrl;$('previewLink').href=longUrl;$('result').classList.add('show');$('resultDesc').textContent=shortened?'단축 URL이 생성되었습니다. 문자나 카카오톡에 붙여 넣어 발송하세요.':'안내 링크는 생성됐지만 단축 서비스 연결에 실패해 원본 링크를 표시합니다.';$('shortStatus').textContent=shortened?'단축 주소는 is.gd에서 생성되며, 안내 내용은 설정한 만료일 이후 고객 화면에서 가려집니다.':'네트워크 또는 단축 서비스 제한으로 단축하지 못했습니다. 잠시 뒤 다시 생성할 수 있습니다.';$('result').scrollIntoView({behavior:'smooth',block:'center'})}catch(e){showError('URL 생성 중 오류가 발생했습니다. 다시 시도해 주세요.')}finally{btn.disabled=false;btn.textContent='고객 안내 단축 URL 생성하기'}};
async function copyText(text,button,label){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent=label;setTimeout(()=>button.textContent=old,1400)}catch{prompt('아래 내용을 복사하세요.',text)}}$('copyLink').onclick=()=>copyText($('generatedLink').value,$('copyLink'),'복사 완료');$('copyMessage').onclick=()=>copyText(`[모두투어 여행 준비 안내]\n\n${cities.map(c=>c.label).join(' · ')} 여행의 날씨, 옷차림, 환율, 확정 일정과 호텔 정보를 아래 링크에서 확인해 주세요.\n\n${$('generatedLink').value}\n\n안내 링크는 설정된 유효기간 이후 자동 종료됩니다.`,$('copyMessage'),'문구 복사 완료');
$('fillSample').onclick=()=>{cities.splice(0,cities.length,{label:'취리히',name:'Zürich',country:'스위스',country_code:'CH',latitude:47.3769,longitude:8.5417,admin1:'취리히'},{label:'루체른',name:'Lucerne',country:'스위스',country_code:'CH',latitude:47.0502,longitude:8.3093,admin1:'루체른'},{label:'프라하',name:'Prague',country:'체코',country_code:'CZ',latitude:50.0755,longitude:14.4378,admin1:'프라하'});renderCities();notesEdited=false;autoNotes(true);$('scheduleUrl').value='https://www.modetour.com/';$('guideInfo').value='인솔자 김모두\n현지 연락처: +41-00-000-0000\n카카오톡 ID: modetour-guide\n비상 상황 발생 시 위 연락처로 연락해 주세요.';$('hotels').innerHTML='';addHotel({name:'Hotel Schweizerhof Zürich',city:'취리히',address:'Bahnhofplatz 7, Zürich',note:'조식 포함 · 중앙역 인근'});addHotel({name:'Grand Hotel Prague Towers',city:'프라하',address:'Kongresová 1, Prague',note:'무료 Wi-Fi'})};
renderCities();autoNotes(false);