import fs from "node:fs/promises";
const FILE=new URL("../public/data/news.json",import.meta.url);const existing=JSON.parse(await fs.readFile(FILE,"utf8"));
const clean=s=>String(s||"").replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const itemsFromXml=(xml,source)=>[...xml.matchAll(/<item\b[\s\S]*?<\/item>/gi)].map((m,i)=>{const x=m[0],pick=t=>clean((x.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,"i"))||[])[1]);return{id:`rss-${source}-${i}-${Date.now()}`,title:pick("title"),titleKo:pick("title"),link:pick("link")||pick("guid"),pubDate:pick("pubDate"),source,category:"미국 현지 읽을거리",readingMinutes:6,bodyVerified:false,depthScore:source==="FanGraphs"?62:52}}).filter(x=>x.title&&x.link);
const feeds=[["MLB.com","https://www.mlb.com/feeds/news/rss.xml"],["FanGraphs","https://blogs.fangraphs.com/feed/"]];
const verified=(existing.items||[]).filter(x=>x.bodyVerified).sort((a,b)=>(b.depthScore||0)-(a.depthScore||0)).slice(0,2);let pool=[];
for(const[source,url]of feeds){try{const r=await fetch(url,{headers:{"user-agent":"today-mlb/1.0"}});if(r.ok)pool.push(...itemsFromXml(await r.text(),source))}catch(e){console.warn(`Feed failed: ${source}`,e.message)}}
const score=x=>(x.source==="FanGraphs"?30:0)+(/how|why|impact|strategy|analysis|inside|adjust|change|development/i.test(x.title)?15:0)-(/tracker|every move|traded to|deal$/i.test(x.title)?12:0)+(x.depthScore||0);
pool.sort((a,b)=>score(b)-score(a)||new Date(b.pubDate||0)-new Date(a.pubDate||0));
const selected=[...verified],seen=new Set(selected.map(x=>(x.link||x.title).replace(/[?#].*$/,"")).filter(Boolean));for(const x of pool){const key=(x.link||x.title).replace(/[?#].*$/,"");if(!key||seen.has(key))continue;seen.add(key);selected.push(x);if(selected.length===4)break}
for(const x of existing.items||[]){if(selected.length===4)break;const key=(x.link||x.title).replace(/[?#].*$/,"");if(!key||seen.has(key))continue;seen.add(key);selected.push(x)}
const out={...existing,items:selected.slice(0,4),selectedCount:Math.min(4,selected.length),policy:"two_verified_longform_plus_two_current_us_items",updatedAt:new Date().toISOString()};await fs.writeFile(FILE,JSON.stringify(out,null,2));console.log(`Selected reading items: ${out.selectedCount}`);